### ISSUE TITLE
Example using SQL Server

### ISSUE THREAD

**Issue by shortybowker** [Steveiwonder/DataMasker#4] opened 2018-04-19 14:49 UTC
Hi, 
Using your example, I get 'Config' does not contain a definition for 'LoadConfig' - Config.Config seems to work though - which one is correct?

Is there like full doumentation for this?

I can't seem to ligin to a SQL Server DB with Windows Authentication - e.g. i leave the username / password blank it doesn't log in - if I leave them out of the config, same problem.

Also, what I in reality want to do is this ...
Login to Source DB on server1
login to target DB on server 2

loop through tables/data from Source, and UpdateRow(?) on Target DB

Is this possible?

Regards,
Steve Bowker

**Comment by shortybowker** [comment] 2018-04-19 15:39
FYI - here is an example ConnectionString that we use ...

ConnectionString="Auto Translate=True;Integrated Security=SSPI;Tag with column collation when possible=False;Data Source=OurServer;Initial Catalog=OurDatabase;Use Procedure for Prepare=1;Provider=SQLOLEDB.1;Persist Security Info=True;Use Encryption for Data=False;Packet Size=4096"

**Comment by Steveiwonder** [comment] 2018-04-20 07:43
> Using your example, I get 'Config' does not contain a definition for 'LoadConfig' - Config.Config seems to work though - which one is correct?

I pulled down the latest code on master to a fresh VM and the examples as is, work just fine. So I'm not entirely sure what is going on with your copy. Could you zip up the whole directory and upload it?

>Is there like full doumentation for this?

https://github.com/Steveiwonder/DataMasker/blob/develop/README.md


>Also, what I in reality want to do is this ...
>Login to Source DB on server1
>login to target DB on server 2
>loop through tables/data from Source, and UpdateRow(?) on Target DB
>Is this possible?

Not out of the box using the runner/config options (assuming by the ? means based on condition)
You could write your own using something similar to Example1
```
public static void Example1()
{
	Config config = LoadConfig(1);
	IDataMasker dataMasker = new DataMasker(new DataGenerator(config.DataGeneration));
	IDataSource dataSource = DataSourceProvider.Provide(config.DataSource.Type, config.DataSource);

	foreach (TableConfig tableConfig in config.Tables)
	{
		IEnumerable<IDictionary<string, object>> rows = dataSource.GetData(tableConfig);
		foreach (IDictionary<string, object> row in rows)
		{
			if ( /*INSERT YOUR CONDITION HERE*/)
			{
				dataMasker.Mask(row, tableConfig);

				//update per row
				dataSource.UpdateRow(row, tableConfig);
			}
		}

		//update all rows
		//dataSource.UpdateRows(rows, tableConfig);
	}
}
```

**Comment by shortybowker** [comment] 2018-04-20 08:14
Hi,
Zip file attached.
You didn't answer my Q re logging in using windows authentication (no user / pwd)
Your Example1 - would this work for ...
source table has let's say 500 records, target table currently has 0 records - so in essence I'm trying to read source records, scramble in memory, and write new records on target table/DB

Regards,
Steve
[DataScrambling.zip](https://github.com/Steveiwonder/DataMasker/files/1931283/DataScrambling.zip)

**Comment by shortybowker** [comment] 2018-04-20 08:30
sorry, closed by mistake

**Comment by Steveiwonder** [comment] 2018-04-20 09:12
Sorry I missed the windows auth question. It is not currently supported but I've raised https://github.com/Steveiwonder/DataMasker/issues/5 to add support. I'll do it shortly

> Your Example1 - would this work for ...
> source table has let's say 500 records, target table currently has 0 records - so in essence I'm trying to read source records, scramble in memory, and write new records on target table/DB

Not currently, that is data migration.  I could add a feature for inserting but this isn't what DataMasker was intended for, it's for masking existing data in a target database. There are plenty of free tools which you could use to migrate the data from source to target and then use DataMasker to mask the data after. If you do really want it raise a feature and I'll considering adding it but cannot guarantee when.

Now.. for your `Config.LoadConfig` error, this is my fault the documentation is incorrect it should be `Config.Load("")` - Sorry, I've update the docs and will push them soon

edit: docs updated

**Comment by Steveiwonder** [comment] 2018-04-20 10:03
I've added support for a connectionString in the config.json file, you can now supply the following as your dataSource
```
"dataSource": {
    "type": "SqlServer",
    "config": {
      "connectionString": "Data Source=(localdb)\\mssqllocaldb;Initial Catalog=Clients;Integrated Security=SSPI;"
    }
  },
```

Let me know if you need anything else, otherwise please close the issue. Thanks :)

**Comment by shortybowker** [comment] 2018-05-04 09:40
Hi,
How do you instantiate the dataMasker?
In your example, it falls over with ‘object reference not set to an instance of an object’

There is an instantiation of the dataSource, but not the dataMasker

Regards,
Steve

**Comment by shortybowker** [comment] 2018-05-04 10:15
Hi,
Sorry, got it working, but it does fall over when I use Bogus as the “type”: in the json (tables section)
Do I need to instantiate Bogus, and if so, how?

Also, how would I change individual address lines?

e.g.

"name": "AddressLine1",
  "type": "FullAddress",
  "retainNullValues": true,

We actually have fields like AddressLine1,AddressLine2 etc – so FullAddress is no good for us

Regards,
Steve

From: Steve Bowker
Sent: 04 May 2018 10:40
To: 'Steveiwonder/DataMasker'; Steveiwonder/DataMasker
Cc: Author
Subject: RE: [Steveiwonder/DataMasker] Example using SQL Server (#4)

Hi,
How do you instantiate the dataMasker?
In your example, it falls over with ‘object reference not set to an instance of an object’

There is an instantiation of the dataSource, but not the dataMasker

Regards,
Steve

**Comment by Steveiwonder** [comment] 2018-05-04 11:39
When you use the type `Bogus` you **must** supply a `stringFormatPattern` value.
Something like this:
```
{
  "name": "Address",
  "type": "Bogus",
  "stringFormatPattern": "{{address.fullAddress}}"
}
```

As for your AddressLine1 etc
Take a look at https://github.com/bchavez/Bogus#bogus-api-support you can supply any of the values from here so to get AddressLine1 you could try the following config

```
{
  "name": "AddressLine1",
  "type": "Bogus",
  "stringFormatPattern": "{{address.buildingNumber}} {{address.streeName}}"
}
```

If you need anything else please let me know

**Comment by shortybowker** [comment] 2018-05-04 14:47
Thx ☺

**Closed as completed** 2018-05-17 19:32 UTC
Labels: help wanted
